  backend:
    restart: always
    build:
      context: backend
    env_file:
      - backend/.env
    environment:
      - DB_ADDRESS=mongodb://root:example@mongo:27017/weblarek
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    networks:
      - internal
    depends_on:
      - mongo
      condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s